-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 23:35:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Message_board
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Message_board
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Message_board` DEFAULT CHARACTER SET utf8 ;
USE `Message_board` ;

-- -----------------------------------------------------
-- Table `Message_board`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`user_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`personal_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`personal_data` (
  `id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `personal_to_user`
    FOREIGN KEY (`id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`ad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NULL,
  `text` VARCHAR(100) NOT NULL,
  `price` DECIMAL NULL,
  `image` VARCHAR(45) NULL,
  `seller_id` INT NOT NULL,
  `category_id` INT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `ad_to_user_idx` (`seller_id` ASC) VISIBLE,
  INDEX `ad_to_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `ad_to_user`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ad_to_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `Message_board`.`category` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `user_from_id` INT NOT NULL,
  `ad_id` INT NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `comment_to_user_idx` (`user_from_id` ASC) VISIBLE,
  INDEX `comment_to_ad_idx` (`ad_id` ASC) VISIBLE,
  CONSTRAINT `comment_to_user`
    FOREIGN KEY (`user_from_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comment_to_ad`
    FOREIGN KEY (`ad_id`)
    REFERENCES `Message_board`.`ad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback` INT NULL,
  `user_from_id` INT NULL,
  `user_whom_id` INT NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `ranking_to_user_from_idx` (`user_from_id` ASC) VISIBLE,
  INDEX `ranking_to_user_whom_idx` (`user_whom_id` ASC) VISIBLE,
  CONSTRAINT `ranking_to_user_from`
    FOREIGN KEY (`user_from_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ranking_to_user_whom`
    FOREIGN KEY (`user_whom_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`user_2_ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`user_2_ad` (
  `user_id` INT NOT NULL,
  `ad_id` INT NOT NULL,
  INDEX `to_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `to_ad_idx` (`ad_id` ASC) VISIBLE,
  CONSTRAINT `to_user_(user_2_ad)`
    FOREIGN KEY (`user_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `to_ad`
    FOREIGN KEY (`ad_id`)
    REFERENCES `Message_board`.`ad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  `created` DATE NULL,
  `updated` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `message_to_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `message_to_chat_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `message_to_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `message_to_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `Message_board`.`chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message_board`.`user_2_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message_board`.`user_2_chat` (
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  INDEX `to_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `to_chat_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `to_user_(user_2_chat)`
    FOREIGN KEY (`user_id`)
    REFERENCES `Message_board`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `to_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `Message_board`.`chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
